import { Injectable } from "@angular/core";
import { Observable, of } from "rxjs";
import { Student } from "../../../src/components/masters/students/models/student.model";

@Injectable({
  providedIn: "root",
})
export class StudentService {
  private students: Student[] = [
    {
      id: "1",
      no: "01",
      name: "Sophia Wilson",
      rollNum: "5223cs009",
      className: "12 A",
      profilePic: "https://via.placeholder.com/32x32/e91e63/ffffff?text=SW",
      accomType: "Hosteller",
      transport: "No",
      location: "Singanallur",
      contact: "82486 69086",
      rank: "001",
      points: "28980",
      firstName: "Sophia",
      lastName: "Wilson",
      gender: "Female",
      dateOfBirth: "15/05/2007",
      section: "A",
    },
    {
      id: "2",
      no: "02",
      name: "Sophia Brown",
      rollNum: "5223cs010",
      className: "12 A",
      profilePic: "https://via.placeholder.com/32x32/e91e63/ffffff?text=SB",
      accomType: "Hosteller",
      transport: "No",
      location: "Singanallur",
      contact: "82486 69086",
      rank: "002",
      points: "28980",
      firstName: "Sophia",
      lastName: "Brown",
      gender: "Female",
      dateOfBirth: "20/03/2007",
      section: "A",
    },
    {
      id: "3",
      no: "03",
      name: "Sophia Anderson",
      rollNum: "5223cs011",
      className: "12 A",
      profilePic: "https://via.placeholder.com/32x32/e91e63/ffffff?text=SA",
      accomType: "Hosteller",
      transport: "No",
      location: "Singanallur",
      contact: "82486 69086",
      rank: "003",
      points: "28980",
      firstName: "Sophia",
      lastName: "Anderson",
      gender: "Female",
      dateOfBirth: "10/07/2007",
      section: "A",
    },
    {
      id: "4",
      no: "04",
      name: "Sophia Wilson",
      rollNum: "5223cs012",
      className: "12 A",
      profilePic: "https://via.placeholder.com/32x32/e91e63/ffffff?text=SW",
      accomType: "Hosteller",
      transport: "No",
      location: "Singanallur",
      contact: "82486 69086",
      rank: "004",
      points: "28980",
      firstName: "Sophia",
      lastName: "Wilson",
      gender: "Female",
      dateOfBirth: "25/09/2007",
      section: "A",
    },
    {
      id: "5",
      no: "05",
      name: "Sophia Williams",
      rollNum: "5223cs013",
      className: "12 A",
      profilePic: "https://via.placeholder.com/32x32/e91e63/ffffff?text=SW",
      accomType: "Hosteller",
      transport: "No",
      location: "Singanallur",
      contact: "82486 69086",
      rank: "005",
      points: "28980",
      firstName: "Sophia",
      lastName: "Williams",
      gender: "Female",
      dateOfBirth: "05/12/2007",
      section: "A",
    },
    {
      id: "6",
      no: "06",
      name: "Sophia Wilson",
      rollNum: "5223cs014",
      className: "12 A",
      profilePic: "https://via.placeholder.com/32x32/e91e63/ffffff?text=SW",
      accomType: "Hosteller",
      transport: "No",
      location: "Singanallur",
      contact: "82486 69086",
      rank: "006",
      points: "28980",
      firstName: "Sophia",
      lastName: "Wilson",
      gender: "Female",
      dateOfBirth: "18/01/2007",
      section: "A",
    },
    {
      id: "7",
      no: "07",
      name: "Sophia Wilson",
      rollNum: "5223cs015",
      className: "12 A",
      profilePic: "https://via.placeholder.com/32x32/e91e63/ffffff?text=SW",
      accomType: "Hosteller",
      transport: "No",
      location: "Singanallur",
      contact: "82486 69086",
      rank: "007",
      points: "28980",
      firstName: "Sophia",
      lastName: "Wilson",
      gender: "Female",
      dateOfBirth: "30/04/2007",
      section: "A",
    },
    {
      id: "8",
      no: "08",
      name: "Sophia Wilson",
      rollNum: "5223cs016",
      className: "12 A",
      profilePic: "https://via.placeholder.com/32x32/e91e63/ffffff?text=SW",
      accomType: "Hosteller",
      transport: "No",
      location: "Singanallur",
      contact: "82486 69086",
      rank: "008",
      points: "28980",
      firstName: "Sophia",
      lastName: "Wilson",
      gender: "Female",
      dateOfBirth: "12/08/2007",
      section: "A",
    },
    {
      id: "9",
      no: "09",
      name: "Sophia Wilson",
      rollNum: "5223cs017",
      className: "12 A",
      profilePic: "https://via.placeholder.com/32x32/e91e63/ffffff?text=SW",
      accomType: "Hosteller",
      transport: "No",
      location: "Singanallur",
      contact: "82486 69086",
      rank: "009",
      points: "28980",
      firstName: "Sophia",
      lastName: "Wilson",
      gender: "Female",
      dateOfBirth: "03/11/2007",
      section: "A",
    },
    {
      id: "10",
      no: "10",
      name: "Sophia Wilson",
      rollNum: "5223cs018",
      className: "12 A",
      profilePic: "https://via.placeholder.com/32x32/e91e63/ffffff?text=SW",
      accomType: "Hosteller",
      transport: "No",
      location: "Singanallur",
      contact: "82486 69086",
      rank: "010",
      points: "28980",
      firstName: "Sophia",
      lastName: "Wilson",
      gender: "Female",
      dateOfBirth: "14/06/2007",
      section: "A",
    },
    {
      id: "11",
      no: "11",
      name: "Sophia Wilson",
      rollNum: "5223cs019",
      className: "12 A",
      profilePic: "https://via.placeholder.com/32x32/e91e63/ffffff?text=SW",
      accomType: "Hosteller",
      transport: "No",
      location: "Singanallur",
      contact: "82486 69086",
      rank: "011",
      points: "28980",
      firstName: "Sophia",
      lastName: "Wilson",
      gender: "Female",
      dateOfBirth: "27/02/2007",
      section: "A",
    },
    {
      id: "12",
      no: "12",
      name: "Sophia Wilson",
      rollNum: "5223cs020",
      className: "12 A",
      profilePic: "https://via.placeholder.com/32x32/e91e63/ffffff?text=SW",
      accomType: "Hosteller",
      transport: "No",
      location: "Singanallur",
      contact: "82486 69086",
      rank: "012",
      points: "28980",
      firstName: "Sophia",
      lastName: "Wilson",
      gender: "Female",
      dateOfBirth: "09/10/2007",
      section: "A",
    },
  ];

  getStudents(): Observable<Student[]> {
    return of(this.students);
  }

  addStudent(student: Student): Observable<Student> {
    student.id = (this.students.length + 1).toString();
    student.no = (this.students.length + 1).toString().padStart(2, "0");
    this.students.push(student);
    return of(student);
  }

  updateStudent(student: Student): Observable<Student> {
    const index = this.students.findIndex((s) => s.id === student.id);
    if (index > -1) {
      this.students[index] = student;
    }
    return of(student);
  }

  deleteStudent(rollNum: string): Observable<boolean> {
    const initialLength = this.students.length;
    this.students = this.students.filter((s) => s.rollNum !== rollNum);
    return of(this.students.length < initialLength);
  }
}
